# Generated by Django 4.2.10 on 2024-08-20 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_price_group_course_group_title_lesson_course_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='B_value',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10, verbose_name='Баланс пользователя'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='What_a_Course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='На какой курс подписан'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='Who_use',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Кто подписан'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='name_of_subscription',
            field=models.CharField(default=1, max_length=250, unique=True, verbose_name='Название подписки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscription',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
