# Generated by Django 4.2.10 on 2024-08-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_balance_b_value_subscription_what_a_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='Flag_subscripton',
            field=models.BooleanField(choices=[(True, 'ДА'), (False, 'Нет')], default=False, verbose_name='Есть подписка?'),
        ),
    ]
