# Generated by Django 4.2.10 on 2024-08-20 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_subscription_flag_subscripton'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='What_a_Course',
        ),
    ]
