# Generated by Django 4.2.10 on 2024-08-20 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_subscription_what_a_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Баланс пользователя'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscription',
            name='Who_use',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Кто подписан'),
            preserve_default=False,
        ),
    ]
