# Generated by Django 4.2.10 on 2024-08-20 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_subscription_what_a_course'),
        ('courses', '0002_course_price_group_course_group_title_lesson_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='What_a_Course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.subscription', verbose_name='На какой курс подписан'),
        ),
    ]
