# Generated by Django 4.2.10 on 2024-08-20 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_what_a_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='courses_in_stock',
            field=models.IntegerField(default=1, verbose_name='Количество курсов в наличии'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='crs',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
            preserve_default=False,
        ),
    ]
