# Generated by Django 4.2.10 on 2024-08-20 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_courses_in_stock_lesson_crs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='crs',
        ),
    ]
