# Generated by Django 4.2.10 on 2024-08-20 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_subscription_what_a_course'),
        ('courses', '0006_remove_course_what_a_course_course_what_a_sub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='What_a_sub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.subscription', verbose_name='Какая подписка'),
        ),
    ]
